services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn django_postgresql.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_postgresql.settings
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
