# Generated by Django 4.2.20 on 2025-06-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('original_price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Ngừng bán'), (1, 'Đang bán'), (2, 'Hết hàng')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
    ]
